### ISSUE TITLE
zap_stop does not stop ZaProxy

### ISSUE THREAD

**Issue by AlbanAndrieu** [TeamPraxis/grunt-zaproxy#2] opened 2015-06-15 10:48 UTC
Hi,

I have the following issue.

Locally on my workstation : An Ubuntu 14 LTS : 3.13.0-54-generic
I am doing : 
export PATH=/usr/local/zap/zap-2.3.0/:${PATH}
grunt zap_start
Zap is started.

Then I am doing

grunt zap_stop
ZaProxy is never shutdowned.

Please see following project for more information
https://github.com/AlbanAndrieu/nabla-servers-bower-sample/

And a Jenkins build
http://home.nabla.mobi:8380/jenkins/job/nabla-servers-bower-sample-nightly/
(I am trying other solution, so it might fail for other reason).

BTW ; I will create another issue about ZaProxy that is not started using Jenkins

Thank in advance for your help,

Regards,

Alban Andrieu

**Comment by khamasaki** [comment] 2015-06-15 20:28
Hi, is there any output from the grunt zap_stop command? I am unable to reproduce your problem, but I am running on Mac OS (I was able to successfully stop zap using your github project).

**Comment by AlbanAndrieu** [comment] 2015-06-16 09:45
Hi,

The only log I have are:

Running "zap_start" task
Starting ZAProxy: ...........OK

Running "acceptance-test" task
OK

Running "protractor:run" (protractor) task
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.25.40.76:55952/wd/hub
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] firefox #1 passed

Running "zap_alert" task
Waiting for scanning to finish: OK
Checking for alerts: OK

Running "zap_stop" task
Stopping ZAProxy: ZAProxy does not appear to be running.

Done, without errors.

Do you know how I can get more log info?

Best regards,

Alban

**Comment by khamasaki** [comment] 2015-06-17 19:22
Fixed with #4. Closing.

**Closed by khamasaki** 2015-06-17 19:22 UTC
